Fixes

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -57,6 +57,15 @@ else
     find . -type f -name '*.bak*' -delete
 fi
 
+if ! command -v latexmk; then
+    echo "latexmk could not be found. Run with --no-verify to skip the check."
+    exit 1
+else
+    # Rebuild
+    latexmk -cd -pdf "src/source.tex" < /dev/null 2> /dev/null
 
-# If there are whitespace errors, print the offending file names and fail.
-exec git diff-index --check --cached $against --
+    # Move to out directory
+    mv "src/source.pdf" "out/source.pdf"
+fi
+
+git add .
