Fixes

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -55,5 +55,17 @@ else
         find . -type f -path './src/*' -name '*.tex' -exec latexindent -w -m -s -l=indentConfig.yaml {} \;
     } 2> /dev/null
     find . -type f -name '*.bak*' -delete
-    git add .
 fi
+
+if ! command -v latexmk; then
+    echo "latexmk could not be found. Run with --no-verify to skip the check."
+    exit 1
+else
+    # Rebuild
+    latexmk -cd -pdf "src/source.tex" < /dev/null 2> /dev/null
+
+    # Move to out directory
+    mv "src/source.pdf" "out/source.pdf"
+fi
+
+git add .
